spring:
  datasource:
    url: jdbc:mysql://192.168.132.130:3306/seumstc?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 123456
    username: root
  servlet:
    multipart:
      ##上传请求的大小
      max-request-size: 10MB
      ##上传的单文件大小
      max-file-size: 10MB
  application:
    # 服务名
    name: blog-application
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 192.168.132.131:8848
  redis:
    port: 6379
    host: 192.168.132.130
    password: wanghuan
    timeout: 1s
    database: 7

  cache:
    redis:
      time-to-live: 600s
server:
  # 服务端口
  port: 8080
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
mybatis:
  config-location: "classpath:mybatis-config.xml"