spring:
  servlet:
    multipart:
      ##上传请求的大小
      max-request-size: 10MB
      ##上传的单文件大小
      max-file-size: 10MB
  application:
    # 服务名
    name: blog-application
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 192.168.132.130:8848
  redis:
    port: 6379
    host: 192.168.132.130
    password: wanghuan
    timeout: 1s
    database: 7

  cache:
    redis:
      time-to-live: 600s
server:
  # 服务端口
  port: 8080
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"